// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:88bd8f63-fc91-4160-9d91-da99a6bb08ed",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_mJwEOONGq",
  aws_user_pools_web_client_id: "5acvjnvf3c0sqeojfasvcs7tc7",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://vtykbaqxunb3tobpj4ljf6bbwm.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_content_delivery_bucket: "shareprice-20200226114424-hostingbucket-dev",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_url:
    "http://shareprice-20200226114424-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};

export default awsmobile;
